# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'myFood' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for myFood
pod 'SwiftLint'

  # Pods for Amplify Framework
pod 'amplify-tools'
pod 'Amplify'
pod 'AWSPluginsCore'
pod 'AmplifyPlugins/AWSAPIPlugin'

end
